apiVersion: apps/v1
kind: Deployment
metadata:
  name: inapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipeapp
  template:
    metadata:
      labels:
        app: pipeapp
    spec:
      containers:
        - name: pipeapp-container
          image: daamola3/pipeapp:1.0
          ports:
          - containerPort: 5000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: pipeapp-service
spec:
  selector:
    app: pipeapp
  ports:
    - protocol: TCP
      port: 5000 # Port for internal communication within the cluster
      targetPort: 5000 # Port exposed by pipe-app containers
  type: ClusterIP